# Default values for go-app-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nexo-app-db

Deployment:
  name: go-app-kubernetes
  replicaCount: 1
  image:
    name:  nexo-app-kubernetes
    tag: latest

service:
  name: go-app-kubernetes-svc
  type: NodePort
  port: 8080